import { defineSchema, defineTable } from "convex/server"
import { v } from "convex/values"

export default defineSchema({
  users: defineTable({
    name: v.string(),
    tokenIdentifier: v.string(),
  }).index("by_token", ["tokenIdentifier"]),

  settings: defineTable({
    tenantId: v.string(),
    userId: v.id("users"),
    companyName: v.string(),
    website: v.string(),
    email: v.string(),
    phone: v.string(),
    fax: v.optional(v.string()),
    taxIdentificationNumber: v.optional(v.string()),
    logoUrl: v.optional(v.string()),
    mailingAddress: v.object({
      country: v.string(),
      address: v.string(),
      city: v.string(),
      state: v.string(),
      zipCode: v.string(),
    }),
    shopAddress: v.object({
      country: v.string(),
      address: v.string(),
      city: v.string(),
      state: v.string(),
      zipCode: v.string(),
    }),
    ccEmails: v.array(v.string()),
    autoSaveRetailVehicles: v.boolean(),
    autoSaveWholesaleVehicles: v.boolean(),
    disableMultiCarEstimates: v.boolean(),
    requireWorkOrdersFromEstimate: v.boolean(),
    convertEstimatesToInvoices: v.boolean(),
    activateTipsOnPayments: v.boolean(),
    invoicePrefix: v.string(),
    nextInvoiceNumber: v.number(),
    requiredFields: v.object({
      customerName: v.boolean(),
      customerPhone: v.boolean(),
      customerEmail: v.boolean(),
      vehicleYear: v.boolean(),
      vehicleMake: v.boolean(),
      vehicleModel: v.boolean(),
      vehicleColor: v.boolean(),
      vehicleMiles: v.boolean(),
      vehicleVin: v.boolean(),
      vehicleLicensePlate: v.boolean(),
    }),
    pdfOptions: v.object({
      showVehicleImages: v.boolean(),
      showVehicleDiagram: v.boolean(),
    }),
    signatureDisclosures: v.object({
      invoiceDisclosure: v.string(),
      estimateDisclosure: v.string(),
    }),
    textTemplate: v.object({
      language: v.string(),
      defaultMessage: v.string(),
    }),
    stripeConnectedAccountId: v.optional(v.string()),
    stripePaymentsEnabled: v.boolean(),
  }).index("by_tenantId", ["tenantId"]),

  transactions: defineTable({
    tenantId: v.string(),
    clientName: v.string(),
    date: v.string(),
    estimateNumber: v.string(),
    invoiceNumber: v.string(),
    amountPaid: v.number(),
    stripeChargeId: v.string(),
    refunded: v.boolean(),
    refundId: v.optional(v.string()),
  }).index("by_tenantId", ["tenantId"]),

  companyRates: defineTable({
    tenantId: v.string(),
    laborRateRI: v.number(),
    laborRatePaint: v.number(),
    laborRateBody: v.number(),
    paintMaterialRate: v.number(),
    laborRateDetail: v.number(),
    taxRate: v.number(),
    pdrRates: v.object({
      fullFront: v.number(),
      trackPackage: v.number(),
      fullCoverage: v.number(),
      hailMarkupOS: v.boolean(),
      rirrDefaultPricing: v.string(),
      paintBodyDefaultPricing: v.string(),
      flatFee: v.number(),
      interiorDefaultPricing: v.string(),
      interiorFlatFee: v.number(),
    }),
    wheelRates: v.object({
      cosmetic: v.number(),
      remanufactured: v.number(),
      straighten: v.number(),
      backsideRepair: v.number(),
      crackRepair: v.number(),
      powderCoat: v.number(),
      powderCoatTPMSSleeve: v.number(),
      customPaint: v.number(),
      hyperFinish: v.number(),
      machineFinish: v.number(),
      polish: v.number(),
      specialFinish: v.number(),
      twoPieceWheel: v.number(),
      threePieceWheel: v.number(),
      paintCenterCaps: v.number(),
      paintHubcaps: v.number(),
      paintCallipers: v.number(),
      reChromed: v.number(),
      hubcapRepair: v.number(),
      mountAndBalance: v.number(),
      tpmsReset: v.number(),
      ceramicCoating: v.number(),
      tireDisposalFee: v.number(),
    }),
    glassRates: v.object({
      defaultPricingType: v.string(),
      firstRepair: v.number(),
      additionalRepairs: v.number(),
    }),
    tintRates: v.object({
      defaultPricingType: v.string(),
    }),
  }).index("by_tenantId", ["tenantId"]),
})

